using System;

namespace Cybersuite.Abstractions;

/// <summary>
/// Extension methods for <see cref="IAeadService"/> that integrate with <see cref="IAeadNonceStrategy"/>
/// for structural nonce-reuse protection.
/// 
/// Usage:
/// <code>
/// using var nonces = new MonotonicCounterNonceStrategy(aead.NonceSize);
/// aead.EncryptWithStrategy(nonces, key, plaintext, aad, ciphertextOut, nonceOut);
/// </code>
/// </summary>
public static class AeadNonceExtensions
{
    /// <summary>
    /// Encrypts plaintext using a nonce generated by the given <see cref="IAeadNonceStrategy"/>.
    /// The generated nonce is written to <paramref name="nonceOut"/> for use during decryption.
    /// This eliminates the risk of caller-managed nonce reuse.
    /// </summary>
    /// <param name="aead">The AEAD service to encrypt with.</param>
    /// <param name="strategy">Nonce strategy that generates unique nonces per key session.</param>
    /// <param name="key">Opaque handle to the symmetric key.</param>
    /// <param name="plaintext">Plaintext to encrypt.</param>
    /// <param name="associatedData">Associated data (authenticated but not encrypted).</param>
    /// <param name="ciphertextOut">
    /// Destination buffer for ciphertext + tag.
    /// Must be at least <see cref="IAeadService.GetCiphertextSize"/> bytes.
    /// </param>
    /// <param name="nonceOut">
    /// Destination buffer for the generated nonce.
    /// Must be at least <see cref="IAeadService.NonceSize"/> bytes.
    /// The caller must transmit/store this nonce alongside the ciphertext for decryption.
    /// </param>
    /// <exception cref="InvalidOperationException">Nonce space exhausted — re-key required.</exception>
    public static void EncryptWithStrategy(
        this IAeadService aead,
        IAeadNonceStrategy strategy,
        SecretKeyHandle key,
        ReadOnlySpan<byte> plaintext,
        ReadOnlySpan<byte> associatedData,
        Span<byte> ciphertextOut,
        Span<byte> nonceOut)
    {
        ArgumentNullException.ThrowIfNull(aead);
        ArgumentNullException.ThrowIfNull(strategy);

        if (strategy.NonceSize != aead.NonceSize)
            throw new ArgumentException(
                $"Nonce strategy size ({strategy.NonceSize}) does not match AEAD nonce size ({aead.NonceSize}).");

        if (nonceOut.Length < aead.NonceSize)
            throw new ArgumentException(
                $"nonceOut must be at least {aead.NonceSize} bytes.", nameof(nonceOut));

        // Generate a unique nonce via the strategy (throws if exhausted)
        strategy.NextNonce(nonceOut);

        // Encrypt using the strategy-generated nonce
        aead.Encrypt(key, nonceOut[..aead.NonceSize], plaintext, associatedData, ciphertextOut);
    }
}
